version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # emplacement du fichier de config gradle, se trouve Ã  la racine
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    shudule:
      interval: "weekly"
